use super::kerning::KerningClasses;

#[derive(Debug, Clone)]
pub struct AtlasPageMeta {
    pub w: u32,
    pub h: u32,
}

#[derive(Debug, Clone)]
pub struct GlyphLayerMeta {
    pub advances: Vec<f32>,
    pub offset_x: Vec<f32>,
    pub offset_y: Vec<f32>,
    /// Flat interleaved: page, x, y, w, h per glyph.
    pub rects: Vec<u32>,
}

#[derive(Debug, Clone)]
pub struct FontMetaV2 {
    pub line_height: u32,
    pub baseline: u32,
    pub px: f32,
    pub charset: String,
    pub pages: Vec<AtlasPageMeta>,
    pub glyphs: GlyphLayerMeta,
    pub kerning: KerningClasses,
    pub outline: Option<GlyphLayerMeta>,
}

pub fn serialize_font_meta_luau(meta: &FontMetaV2) -> String {
    let mut s = String::from("-- This file is automatically @generated by truffle.\n");
    s.push_str("-- DO NOT EDIT MANUALLY.\n\n");
    s.push_str("local font = ");
    s.push_str(&serialize_meta_table(meta, false));
    s.push_str("\n");
    if meta.outline.is_some() {
        s.push_str("local outline = ");
        s.push_str(&serialize_outline_table(meta));
        s.push_str("\n");
    }
    s.push_str("return {\n\tfont = font,\n");
    if meta.outline.is_some() {
        s.push_str("\toutline = outline,\n");
    }
    s.push_str("}\n");
    s
}

fn serialize_outline_table(meta: &FontMetaV2) -> String {
    let outline = meta.outline.as_ref().expect("outline present");
    let mut parts = vec!["{".to_string()];
    parts.push(format!("\tlineHeight = {},", meta.line_height));
    parts.push(format!("\tbaseline = {},", meta.baseline));
    parts.push(format!("\tpx = {},", float_luau(meta.px)));
    parts.push(format!(
        "\tcharset = {},",
        serde_json::to_string(&meta.charset).unwrap()
    ));
    parts.push("\tpages = {".to_string());
    for page in &meta.pages {
        parts.push(format!("\t\t{{ w = {}, h = {} }},", page.w, page.h));
    }
    parts.push("\t},".to_string());
    push_glyph_arrays(&mut parts, outline, "\t");
    parts.push("\tkerning = font.kerning,".to_string());
    parts.push("}".to_string());
    parts.join("\n")
}

fn serialize_meta_table(meta: &FontMetaV2, _full: bool) -> String {
    let mut parts = vec!["{".to_string()];
    parts.push(format!("\tlineHeight = {},", meta.line_height));
    parts.push(format!("\tbaseline = {},", meta.baseline));
    parts.push(format!("\tpx = {},", float_luau(meta.px)));
    parts.push(format!(
        "\tcharset = {},",
        serde_json::to_string(&meta.charset).unwrap()
    ));
    parts.push("\tpages = {".to_string());
    for page in &meta.pages {
        parts.push(format!("\t\t{{ w = {}, h = {} }},", page.w, page.h));
    }
    parts.push("\t},".to_string());
    push_glyph_arrays(&mut parts, &meta.glyphs, "\t");
    push_kerning(&mut parts, &meta.kerning, "\t");
    parts.push("}".to_string());
    parts.join("\n")
}

fn push_glyph_arrays(parts: &mut Vec<String>, layer: &GlyphLayerMeta, indent: &str) {
    parts.push(format!("{indent}advances = {{"));
    push_float_list(parts, &layer.advances, indent);
    parts.push(format!("{indent}}},"));

    parts.push(format!("{indent}offsetX = {{"));
    push_float_list(parts, &layer.offset_x, indent);
    parts.push(format!("{indent}}},"));

    parts.push(format!("{indent}offsetY = {{"));
    push_float_list(parts, &layer.offset_y, indent);
    parts.push(format!("{indent}}},"));

    parts.push(format!("{indent}rects = {{"));
    push_u32_list(parts, &layer.rects, indent);
    parts.push(format!("{indent}}},"));
}

fn push_kerning(parts: &mut Vec<String>, kerning: &KerningClasses, indent: &str) {
    parts.push(format!("{indent}kerning = {{"));
    parts.push(format!("{indent}\tleftClass = {{"));
    push_u8_list(parts, &kerning.left_class, indent);
    parts.push(format!("{indent}\t}},"));
    parts.push(format!("{indent}\trightClass = {{"));
    push_u8_list(parts, &kerning.right_class, indent);
    parts.push(format!("{indent}\t}},"));
    parts.push(format!(
        "{indent}\tleftCount = {},",
        kerning.left_count
    ));
    parts.push(format!(
        "{indent}\trightCount = {},",
        kerning.right_count
    ));
    parts.push(format!("{indent}\tmatrix = {{"));
    push_float_list(parts, &kerning.matrix, indent);
    parts.push(format!("{indent}\t}},"));
    parts.push(format!("{indent}}},"));
}

fn push_float_list(parts: &mut Vec<String>, values: &[f32], indent: &str) {
    let inner = format!("{indent}\t");
    let mut line = String::from(&inner);
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            line.push_str(", ");
        }
        line.push_str(&float_luau(*v));
        if line.len() > 100 {
            parts.push(line);
            line = String::from(&inner);
        }
    }
    if !line.is_empty() && line != inner {
        parts.push(line);
    }
}

fn push_u32_list(parts: &mut Vec<String>, values: &[u32], indent: &str) {
    let inner = format!("{indent}\t");
    let mut line = String::from(&inner);
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            line.push_str(", ");
        }
        line.push_str(&v.to_string());
        if line.len() > 100 {
            parts.push(line);
            line = String::from(&inner);
        }
    }
    if !line.is_empty() && line != inner {
        parts.push(line);
    }
}

fn push_u8_list(parts: &mut Vec<String>, values: &[u8], indent: &str) {
    let inner = format!("{indent}\t");
    let mut line = String::from(&inner);
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            line.push_str(", ");
        }
        line.push_str(&v.to_string());
        if line.len() > 100 {
            parts.push(line);
            line = String::from(&inner);
        }
    }
    if !line.is_empty() && line != inner {
        parts.push(line);
    }
}

pub fn float_luau(v: f32) -> String {
    if v.is_finite() {
        let s = format!("{v:.6}");
        s.trim_end_matches('0').trim_end_matches('.').to_string()
    } else {
        "0".to_string()
    }
}

pub fn render_font_meta_dts(has_outline: bool) -> String {
    let mut out = "// This file is automatically @generated by truffle.\n\
     // DO NOT EDIT MANUALLY.\n\n\
     export interface FontMetaPage {\n\
     \tw: number;\n\
     \th: number;\n\
     }\n\n\
     export interface FontKerningMeta {\n\
     \tleftClass: number[];\n\
     \trightClass: number[];\n\
     \tleftCount: number;\n\
     \trightCount: number;\n\
     \tmatrix: number[];\n\
     }\n\n\
     export interface FontMetaV2 {\n\
     \tlineHeight: number;\n\
     \tbaseline: number;\n\
     \tpx: number;\n\
     \tcharset: string;\n\
     \tpages: FontMetaPage[];\n\
     \tadvances: number[];\n\
     \toffsetX: number[];\n\
     \toffsetY: number[];\n\
     \trects: number[];\n\
     \tkerning: FontKerningMeta;\n\
     }\n\n\
     export interface FontMetaOutlineV2 extends Omit<FontMetaV2, \"kerning\"> {\n\
     \tkerning: FontKerningMeta | undefined;\n\
     }\n\n\
     declare const font: FontMetaV2;\n\
     export { font };\n"
        .to_string();
    if has_outline {
        out.push_str("\ndeclare const outline: FontMetaOutlineV2;\nexport { outline };\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dts_contains_v2_exports() {
        let dts = render_font_meta_dts(false);
        assert!(dts.contains("export interface FontMetaV2"));
        assert!(dts.contains("declare const font: FontMetaV2"));
    }

    #[test]
    fn compact_serialized_meta_stays_small() {
        use super::super::kerning::KerningClasses;

        let charset = "ABC".to_string();
        let glyphs = GlyphLayerMeta {
            advances: vec![10.0, 12.0, 11.0],
            offset_x: vec![0.0; 3],
            offset_y: vec![0.0; 3],
            rects: vec![0, 1, 2, 3, 4, 0, 5, 6, 7, 8, 0, 9, 10, 11, 12],
        };
        let kerning = KerningClasses {
            left_class: vec![0, 1, 2],
            right_class: vec![0, 1, 2],
            left_count: 3,
            right_count: 3,
            matrix: vec![0.0; 9],
        };
        let meta = FontMetaV2 {
            line_height: 95,
            baseline: 11,
            px: 85.0,
            charset,
            pages: vec![AtlasPageMeta { w: 1024, h: 1024 }],
            glyphs,
            kerning,
            outline: None,
        };

        let luau = serialize_font_meta_luau(&meta);
        assert!(luau.contains("lineHeight = 95"));
        assert!(!luau.contains("version"));
        assert!(luau.lines().count() < 200);
    }
}
